# Site settings
title: "#rezistam"
email: ai@rezistam.ro
description: "Arhiva open-source a protestelor din Piata Victoriei"
baseurl: "" 
url: "https://rezistam.ro"
twitter_username: rezistamro
github_username:  rezistam

markdown: kramdown
